/**
 * patch_data.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Static data layer for the Patch Tracker.
 *
 * Contains three exported-as-globals objects:
 *   POKEMON_IMAGES  — name → filename (Serebii sprites)
 *   PATCH_LINKS     — version → official community.pokemon.com URL
 *   PATCHES         — full patch history array
 *   POKEMON         — Pokémon roster with role/type meta
 *
 * HOW TO UPDATE
 * ─────────────────────────────────────────────────────────────────────────────
 *  New patch    → prepend an entry to PATCHES[]
 *  New Pokémon  → add to POKEMON[] and POKEMON_IMAGES{}
 *  New URL      → add to PATCH_LINKS{}
 */

/* ── Pokémon sprite filenames (Serebii Unite sprites) ──────────────────────── */
const POKEMON_IMAGES = {
  "Absol":              "absol_spe.png",
  "Aegislash":          "aegislash_all.png",
  "Alcremie":           "alcreamie_sup.png",
  "Alolan Ninetales":   "ninetales_atk.png",
  "Alolan Raichu":      "raichu_atk.png",
  "Armarouge":          "armarouge_atk.png",
  "Azumarill":          "azumarill_all.png",
  "Blastoise":          "blastoise_def.png",
  "Blaziken":           "blaziken_all.png",
  "Blissey":            "blissey_sup.png",
  "Buzzwole":           "buzzwole_all.png",
  "Ceruledge":          "ceruledge_all.png",
  "Chandelure":         "chandelure_atk.png",
  "Charizard":          "charizard_all.png",
  "Cinderace":          "cinderace_atk.png",
  "Clefable":           "clefable_sup.png",
  "Comfey":             "comfey_sup.png",
  "Cramorant":          "cramorant_atk.png",
  "Crustle":            "crustle_def.png",
  "Darkrai":            "darkrai_spe.png",
  "Decidueye":          "decidueye_atk.png",
  "Delphox":            "delphox_atk.png",
  "Dhelmise":           "dhelmise_all.png",
  "Dodrio":             "dodrio_spe.png",
  "Dragapult":          "dragapult_atk.png",
  "Dragonite":          "dragonite_all.png",
  "Duraludon":          "duraludon_atk.png",
  "Eldegoss":           "eldegoss_sup.png",
  "Empoleon":           "empoleon_all.png",
  "Espeon":             "espeon_atk.png",
  "Falinks":            "falinks_all.png",
  "Galarian Rapidash":  "rapidash_spe.png",
  "Garchomp":           "garchomp_all.png",
  "Gardevoir":          "gardevoir_atk.png",
  "Gengar":             "gengar_spe.png",
  "Glaceon":            "glaceon_atk.png",
  "Goodra":             "goodra_def.png",
  "Greedent":           "greedent_def.png",
  "Greninja":           "greninja_atk.png",
  "Gyarados":           "gyarados_all.png",
  "Ho-Oh":              "ho-oh_def.png",
  "Hoopa":              "hoopa_sup.png",
  "Inteleon":           "inteleon_atk.png",
  "Lapras":             "lapras_def.png",
  "Latias":             "latias_sup.png",
  "Latios":             "latios_atk.png",
  "Leafeon":            "leafeon_spe.png",
  "Lucario":            "lucario_all.png",
  "Machamp":            "machamp_all.png",
  "Mamoswine":          "mamoswine_def.png",
  "Mega Charizard X":   "mXcharizard_all.png",
  "Mega Charizard Y":   "mYcharizard_all.png",
  "Mega Gyarados":      "mgyarados_all.png",
  "Mega Lucario":       "mlucario_all.png",
  "Mega Mewtwo X":      "mewtwoX_all.png",
  "Mega Mewtwo Y":      "mewtwoY_atk.png",
  "Meowscarada":        "meowscarada_spe.png",
  "Meowth":             "meowth_spe.png",
  "Metagross":          "metagross_all.png",
  "Mew":                "mew_atk.png",
  "Mimikyu":            "mimikyu_all.png",
  "Miraidon":           "miraidon_atk.png",
  "Mr. Mime":           "mr.mime_sup.png",
  "Moltres":            "moltres_all.png",
  "Pawmot":             "pawmot_all.png",
  "Pikachu":            "pikachu_atk.png",
  "Psyduck":            "psyduck_sup.png",
  "Sableye":            "sableye_sup.png",
  "Scizor":             "scizor_all.png",
  "Sirfetch'd":         "sirfetchd_all.png",
  "Slowbro":            "slowbro_def.png",
  "Snorlax":            "snorlax_def.png",
  "Suicune":            "suicune_all.png",
  "Sylveon":            "sylveon_atk.png",
  "Talonflame":         "talonflame_spe.png",
  "Tinkaton":           "tinkaton_all.png",
  "Trevenant":          "trevenant_def.png",
  "Tsareena":           "tsaarena_all.png",
  "Tyranitar":          "tyranitar_all.png",
  "Umbreon":            "umbreon_def.png",
  "Urshifu":            "urshifu_all.png",
  "Vaporeon":           "vaporeon_def.png",
  "Venusaur":           "venusaur_atk.png",
  "Wigglytuff":         "wigglytuff_sup.png",
  "Zacian":             "zacian_all.png",
  "Zapdos":             "zapdos_atk.png",
  "Zeraora":            "zeraora_spe.png",
  "Zoroark":            "zoroark_spe.png",
};

/** Base URL for Serebii Unite sprites */
const IMG_BASE = "https://www.serebii.net/pokemonunite/pokemon/";

/* ── Official patch note URLs ──────────────────────────────────────────────── */
const PATCH_LINKS = {
  "1.22.1.8":  "https://community.pokemon.com/en-us/discussion/23153",
  "1.22.1.7":  "https://community.pokemon.com/en-us/discussion/23049/march-13-2026-patch-notes",
  "1.22.1.5":  "https://community.pokemon.com/en-us/discussion/22912/long-range-tactics-patch-notes",
  "1.22.1.2":  "https://community.pokemon.com/en-us/discussion/22700",
  "1.21.3.13": "https://community.pokemon.com/en-us/discussion/22400",
  "1.21.2.12": "https://community.pokemon.com/en-us/discussion/22057/indomitable-spirit-patch-notes",
  "1.21.1.7":  "https://community.pokemon.com/en-us/discussion/21760/the-roar-of-sea-and-sky-part-2-patch-notes",
  "1.21.1.2":  "https://community.pokemon.com/en-us/discussion/21267/the-roar-of-sea-and-sky-ver-1-21-1-2-patch-notes",
  "1.20.3.11": "https://community.pokemon.com/en-us/discussion/21151/ver-1-20-3-13-patch-notes",
  "1.20.3.10": "https://community.pokemon.com/en-us/discussion/20700",
  "1.20.2.7":  "https://community.pokemon.com/en-us/discussion/20300",
  "1.20.1.5":  "https://community.pokemon.com/en-us/discussion/20200",
  "1.20.1.2":  "https://community.pokemon.com/en-us/discussion/20007",
  "1.19.2.11": "https://community.pokemon.com/en-us/discussion/19600",
  "1.19.2.8":  "https://community.pokemon.com/en-us/discussion/19300",
  "1.19.2.6":  "https://community.pokemon.com/en-us/discussion/19100",
  "1.19.1.4":  "https://community.pokemon.com/en-us/discussion/18800",
  "1.19.1.2":  "https://community.pokemon.com/en-us/discussion/18600",
  "1.18.2.7":  "https://community.pokemon.com/en-us/discussion/18543",
  "1.18.2.6":  "https://community.pokemon.com/en-us/discussion/18543/breath-of-evolution-part-2-ver-1-18-2-6-patch-notes",
  "1.18.2.5":  "https://community.pokemon.com/en-us/discussion/18200",
  "1.18.1.4":  "https://community.pokemon.com/en-us/discussion/17900",
  "1.18.1.3":  "https://community.pokemon.com/en-us/discussion/17700",
  "1.18.1.2":  "https://community.pokemon.com/en-us/discussion/17500",
  "1.17.2.11": "https://community.pokemon.com/en-us/discussion/17200",
  "1.17.2.10": "https://community.pokemon.com/en-us/discussion/17000",
  "1.17.2.8":  "https://community.pokemon.com/en-us/discussion/16800",
  "1.17.1.6":  "https://community.pokemon.com/en-us/discussion/16500",
  "1.17.1.5":  "https://community.pokemon.com/en-us/discussion/16300",
  "1.17.1.2":  "https://community.pokemon.com/en-us/discussion/16000",
};

/* ── Full patch history ────────────────────────────────────────────────────── */
const PATCHES = [
  { version:"1.22.1.8",  name:"Long-Range Tactics Part 2", date:"2026-03-19",
    buffs:["Chandelure","Dragapult","Dragonite","Suicune","Venusaur"],
    nerfs:["Sirfetch'd","Mega Lucario","Meowth","Vaporeon","Zapdos"],
    tweaks:[], notes:"Shop update, Event update, Bug fixes, Text fixes" },

  { version:"1.22.1.7",  name:"Moltres Emergency Nerf", date:"2026-03-13",
    buffs:[], nerfs:["Moltres"], tweaks:[],
    notes:"Moltres released on this date. Emergency nerf même jour suite à un release trop fort." },

  { version:"1.22.1.5",  name:"Long-Range Tactics", date:"2026-03-05",
    buffs:["Cinderace","Cramorant","Garchomp","Gardevoir","Greninja","Latios","Sirfetch'd"],
    nerfs:["Blastoise","Dhelmise","Gyarados","Mega Charizard Y","Mega Gyarados","Mega Mewtwo Y","Mimikyu","Scizor","Zapdos"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bug Fixes, Text Fixes" },

  { version:"1.22.1.2",  name:"Bugfix Day", date:"2026-02-26",
    buffs:[], nerfs:[], tweaks:[], notes:"Bug fixes and stability improvements" },

  { version:"1.21.3.13", name:"Stability Patch", date:"2026-01-27",
    buffs:[], nerfs:["Meowth"], tweaks:[], notes:"Game Stability Improvements, Bug Fixes" },

  { version:"1.21.2.12", name:"Indomitable Spirit", date:"2026-01-22",
    buffs:["Ceruledge","Charizard","Comfey","Darkrai","Galarian Rapidash","Garchomp","Psyduck","Tinkaton","Trevenant"],
    nerfs:["Blaziken","Glaceon","Latias","Mega Charizard Y","Mega Gyarados","Mega Mewtwo X","Vaporeon","Zacian"],
    tweaks:[], notes:"Shop update, Event update, Text fixes, Bug fixes" },

  { version:"1.21.1.7",  name:"Winter Balance", date:"2025-12-25",
    buffs:["Blastoise","Decidueye","Ho-Oh","Inteleon","Machamp","Suicune"],
    nerfs:["Dhelmise","Mega Charizard X","Mimikyu","Miraidon","Vaporeon"],
    tweaks:[], notes:"Shop update, Event update, Text fixes, Map adjustments" },

  { version:"1.21.1.2",  name:"Kyogre Update", date:"2025-12-04",
    buffs:["Glaceon","Gyarados","Ho-Oh","Mega Mewtwo X","Mega Mewtwo Y","Scizor","Tyranitar"],
    nerfs:["Alolan Raichu","Clefable","Darkrai","Latias","Suicune"],
    tweaks:["Dhelmise","Mamoswine"],
    notes:"New feature License Journeys, Ranked matches revamp, Kyogre added to Theia Sky Ruins" },

  { version:"1.20.3.11", name:"November Balance", date:"2025-11-13",
    buffs:["Clefable","Espeon","Leafeon","Mimikyu","Sylveon"],
    nerfs:["Dodrio","Mega Charizard X","Mega Lucario","Zacian"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bug Fixes, Text fixes" },

  { version:"1.20.3.10", name:"October Balance", date:"2025-10-23",
    buffs:["Blaziken","Blissey","Darkrai","Eldegoss","Gengar","Latias","Mr. Mime"],
    nerfs:["Dragonite","Empoleon","Pawmot","Pikachu","Slowbro","Venusaur"],
    tweaks:["Alolan Raichu","Mega Lucario"],
    notes:"Shop Updates, Event Updates, Bug Fixes, Map Adjustments" },

  { version:"1.20.2.7",  name:"Charjabug Scuffle", date:"2025-09-25",
    buffs:["Cinderace","Dragapult","Lucario","Mew","Pawmot","Zoroark"],
    nerfs:["Absol","Aegislash","Comfey","Ceruledge","Umbreon"],
    tweaks:[], notes:"New game mode: Charjabug Scuffle, Shop Updates, Event Updates, Bug fixes" },

  { version:"1.20.1.5",  name:"Empoleon Emergency", date:"2025-09-20",
    buffs:[], nerfs:["Empoleon"], tweaks:[], notes:"Emergency patch targeting Empoleon" },

  { version:"1.20.1.2",  name:"Groudon Update", date:"2025-09-04",
    buffs:["Armarouge","Delphox","Inteleon","Mega Mewtwo X","Mega Mewtwo Y","Trevenant","Venusaur"],
    nerfs:["Charizard","Ho-Oh","Galarian Rapidash","Latios","Zacian"],
    tweaks:["Tinkaton"], notes:"Groudon added to Theia Sky Ruins, Shop Updates, Event Updates" },

  { version:"1.19.2.11", name:"August Balance", date:"2025-08-19",
    buffs:["Alolan Raichu","Comfey","Latias","Miraidon","Urshifu"],
    nerfs:["Alcremie","Ho-Oh","Suicune"],
    tweaks:["Latios"], notes:"Shop Updates, Event Updates, Bug fixes" },

  { version:"1.19.2.8",  name:"Dragons Rising", date:"2025-07-31",
    buffs:["Dragonite","Goodra","Gyarados","Lapras"],
    nerfs:["Galarian Rapidash","Ho-Oh"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bug fixes" },

  { version:"1.19.2.6",  name:"Mid-Season Patch", date:"2025-07-18",
    buffs:["Charizard","Crustle","Gardevoir","Gyarados","Slowbro"],
    nerfs:["Alcremie","Cinderace","Clefable","Garchomp","Hoopa","Psyduck"],
    tweaks:["Ho-Oh","Inteleon","Snorlax","Tsareena"],
    notes:"Shop Updates, Event Updates, Bug fixes" },

  { version:"1.19.1.4",  name:"June Balance", date:"2025-06-27",
    buffs:["Alcremie","Ceruledge","Duraludon","Leafeon"],
    nerfs:["Armarouge","Blaziken","Blissey"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bug fixes" },

  { version:"1.19.1.2",  name:"Season Start Balance", date:"2025-06-05",
    buffs:["Cinderace","Galarian Rapidash","Greedent","Lucario","Mew","Sylveon"],
    nerfs:["Hoopa","Mega Mewtwo X","Mega Mewtwo Y","Pikachu","Psyduck","Snorlax","Suicune"],
    tweaks:["Inteleon","Umbreon"],
    notes:"Held Item changes: Amulet Coin, Shop Updates, Event Updates" },

  { version:"1.18.2.7",  name:"May Balance", date:"2025-05-15",
    buffs:["Blastoise","Blaziken","Clefable","Garchomp"],
    nerfs:["Alolan Raichu","Gyarados","Zacian"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bugfixes" },

  { version:"1.18.2.6",  name:"April Balance", date:"2025-04-24",
    buffs:["Buzzwole","Dragapult","Dragonite","Galarian Rapidash","Venusaur"],
    nerfs:["Absol","Alolan Raichu","Gengar","Goodra","Leafeon","Meowscarada","Suicune","Talonflame","Trevenant","Zeraora"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bugfixes" },

  { version:"1.18.2.5",  name:"Matchmaking Adjustments", date:"2025-04-17",
    buffs:[], nerfs:[], tweaks:[],
    notes:"Matchmaking Adjustments, First to 500 Adjustments, Bug Fixes" },

  { version:"1.18.1.4",  name:"March Balance", date:"2025-03-19",
    buffs:["Comfey","Greninja","Gyarados","Leafeon","Pikachu","Zeraora"],
    nerfs:["Aegislash","Psyduck","Suicune"],
    tweaks:[], notes:"New held items: Accel Bracer and Drive Lens, Shop Updates, Balance Changes" },

  { version:"1.18.1.3",  name:"Minor Tweaks", date:"2025-03-13",
    buffs:[], nerfs:[],
    tweaks:["Absol","Gengar","Meowscarada","Snorlax","Talonflame"],
    notes:"Shop Updates, Event Updates" },

  { version:"1.18.1.2",  name:"Suicune Update", date:"2025-02-27",
    buffs:["Absol","Espeon","Gengar","Meowscarada","Snorlax","Talonflame"],
    nerfs:["Blissey","Miraidon","Tinkaton","Tsareena","Urshifu"],
    tweaks:["Darkrai"],
    notes:"Suicune added, First to 500 mode, Remoat Stadium returns to ranked" },

  { version:"1.17.2.11", name:"Rapidash Fix", date:"2025-02-13",
    buffs:[], nerfs:["Galarian Rapidash"], tweaks:[], notes:"Matchmaking adjustments" },

  { version:"1.17.2.10", name:"February Balance", date:"2025-02-06",
    buffs:["Cramorant","Inteleon","Ho-Oh","Trevenant"],
    nerfs:["Garchomp","Mega Mewtwo Y","Psyduck","Tsareena"],
    tweaks:[], notes:"Shop updates, Event updates" },

  { version:"1.17.2.8",  name:"January Balance", date:"2025-01-16",
    buffs:["Aegislash","Gardevoir","Goodra","Sylveon","Urshifu","Zacian"],
    nerfs:["Alolan Ninetales","Greedent","Psyduck","Umbreon"],
    tweaks:["Blissey","Wigglytuff"], notes:"Shop updates, Event updates" },

  { version:"1.17.1.6",  name:"Christmas Balance", date:"2024-12-26",
    buffs:["Blastoise","Buzzwole","Ceruledge","Eldegoss","Inteleon","Scizor"],
    nerfs:["Mimikyu","Zacian"],
    tweaks:["Darkrai","Psyduck"], notes:"Bug fixes" },

  { version:"1.17.1.5",  name:"Tinkaton Buff", date:"2024-12-16",
    buffs:["Tinkaton"], nerfs:[], tweaks:[], notes:"Bug fixes" },

  { version:"1.17.1.2",  name:"Season 28 Balance", date:"2024-12-05",
    buffs:["Buzzwole","Chandelure","Clefable","Cramorant","Decidueye","Delphox","Dodrio","Inteleon","Metagross","Sableye","Scizor","Talonflame","Tsareena"],
    nerfs:["Absol","Blaziken","Crustle","Duraludon","Garchomp","Leafeon","Machamp","Mr. Mime","Psyduck","Sylveon","Tyranitar","Umbreon","Venusaur","Wigglytuff"],
    tweaks:["Armarouge","Darkrai"],
    notes:"Bug fixes, Matching system improvements, Shop updates, Event updates" },

  { version:"1.16.2.9",  name:"November Balance", date:"2024-11-21",
    buffs:["Cinderace","Goodra","Zeraora"], nerfs:["Darkrai"], tweaks:[],
    notes:"Item Changes: Assault Vest, Rocky Helmet, Rescue Hood, Weakness Policy, Rapid-Fire Scarf, Slick Spoon, Bug fixes" },

  { version:"1.16.2.8",  name:"November 1 Balance", date:"2024-11-01",
    buffs:["Azumarill","Blissey","Espeon","Gardevoir","Glaceon","Greedent","Lapras","Mega Mewtwo Y"],
    nerfs:["Armarouge","Ceruledge","Ho-Oh","Mega Mewtwo X","Miraidon","Pikachu","Zacian"],
    tweaks:[], notes:"Bug fixes" },

  { version:"1.16.2.7",  name:"Darkrai Buff", date:"2024-10-19",
    buffs:["Darkrai"], nerfs:[], tweaks:[], notes:"Bug fixes" },

  { version:"1.16.2.6",  name:"October Balance", date:"2024-10-17",
    buffs:["Alolan Ninetales","Blastoise","Lucario","Machamp","Snorlax","Zoroark"],
    nerfs:["Armarouge","Charizard","Cramorant","Delphox","Dragapult","Dragonite","Gyarados","Mamoswine","Urshifu"],
    tweaks:[], notes:"Shop updates, Event updates, Bug fixes, New gift code: BALANCE1017" },

  { version:"1.16.1.4",  name:"Goal Hacker Update", date:"2024-09-27",
    buffs:[], nerfs:[], tweaks:[],
    notes:"New Battle Item: Goal Hacker, Battle Item adjustments, Bug fixes" },

  { version:"1.16.1.2",  name:"Armarouge Release", date:"2024-09-05",
    buffs:["Buzzwole","Gengar","Mimikyu","Pikachu","Sylveon"],
    nerfs:["Blaziken","Ceruledge","Ho-Oh","Slowbro","Zacian"],
    tweaks:[], notes:"Armarouge added to Aeos Island, Shop updates, Event updates" },

  { version:"1.15.1.7",  name:"WCS Special", date:"2024-08-22",
    buffs:["Greninja","Glaceon","Inteleon"], nerfs:[], tweaks:[],
    notes:"WCS Commemorative Special Sale, Shop Updates, Event Updates" },

  { version:"1.15.1.5",  name:"Shop Update", date:"2024-07-31",
    buffs:[], nerfs:[], tweaks:[], notes:"Shop updates, Event updates, Bug fixes" },

  { version:"1.15.1.3",  name:"Ho-Oh Tweak", date:"2024-07-25",
    buffs:[], nerfs:[], tweaks:["Ho-Oh"], notes:"Shop updates, Event updates, Bug fixes" },

  { version:"1.15.1.2",  name:"3rd Anniversary Balance", date:"2024-07-16",
    buffs:["Ceruledge","Chandelure","Charizard","Clefable","Delphox","Gyarados","Pikachu","Talonflame","Urshifu"],
    nerfs:["Cramorant","Dodrio","Falinks","Mega Mewtwo X","Mega Mewtwo Y","Meowscarada","Miraidon","Sylveon","Zoroark"],
    tweaks:[], notes:"Shop Updates, Event Updates, Bug fixes" },

  { version:"1.14.2.10", name:"June Balance", date:"2024-06-19",
    buffs:["Absol","Blaziken","Duraludon","Garchomp","Mimikyu","Mr. Mime","Slowbro","Venusaur"],
    nerfs:["Hoopa","Leafeon","Miraidon","Scizor","Trevenant","Tyranitar"],
    tweaks:[], notes:"Bug fixes, Text fixes, Pika Party event" },

  { version:"1.14.2.9",  name:"Ceruledge Release", date:"2024-06-13",
    buffs:[], nerfs:[], tweaks:[], notes:"Ceruledge released, Shop updates, Event updates" },

  { version:"1.14.1.6",  name:"May Balance", date:"2024-05-13",
    buffs:["Blissey","Cramorant","Decidueye","Metagross","Tyranitar"],
    nerfs:["Blastoise","Delphox","Glaceon","Gyarados","Mew"],
    tweaks:[], notes:"Bug fix, Text correction" },

  { version:"1.14.1.5",  name:"April Balance", date:"2024-04-16",
    buffs:["Aegislash","Azumarill","Gyarados","Hoopa","Machamp","Snorlax","Umbreon"],
    nerfs:["Buzzwole","Eldegoss","Espeon","Mega Mewtwo Y","Meowscarada","Zoroark"],
    tweaks:["Greedent","Miraidon","Trevenant","Zeraora"],
    notes:"Text fixes, Dragon Carnival Share event" },

  { version:"1.14.1.4",  name:"March Balance", date:"2024-03-12",
    buffs:["Charizard","Greedent","Scizor"],
    nerfs:["Clefable","Glaceon","Inteleon","Miraidon","Umbreon"],
    tweaks:["Blaziken","Gengar","Leafeon","Trevenant"],
    notes:"Text fixes, Item Update: Muscle Band" },

  { version:"1.14.1.2",  name:"Draft Update", date:"2024-02-27",
    buffs:["Zacian","Meowscarada","Leafeon","Gyarados","Pikachu","Blissey","Trevenant","Delphox"],
    nerfs:["Dragapult","Crustle","Dragonite"],
    tweaks:["Mega Mewtwo X","Mega Mewtwo Y","Mimikyu","Metagross","Absol","Blaziken"],
    notes:"Draft pick added in Ranked Matches, Bans increased to 2, Item Updates" },

  { version:"1.13.1.4",  name:"January Balance", date:"2024-01-09",
    buffs:["Cinderace","Gardevoir","Metagross","Sylveon","Wigglytuff","Zeraora"],
    nerfs:["Dodrio","Lapras","Zacian"],
    tweaks:[], notes:"" },

  { version:"1.13.1.3",  name:"December Tweaks", date:"2023-12-12",
    buffs:["Meowscarada"], nerfs:[],
    tweaks:["Dodrio","Hoopa","Talonflame","Zacian"],
    notes:"Action timing restored to original setting" },

  { version:"1.13.1.2",  name:"Solo Challenge Update", date:"2023-12-05",
    buffs:["Alolan Ninetales","Cramorant","Dragapult","Greninja","Mr. Mime","Tsareena"],
    nerfs:["Hoopa","Inteleon","Mew","Mimikyu","Urshifu"],
    tweaks:[], notes:"New Items: Charging Charm, Resonant Guard, New Game Mode: Solo Challenge" },

  { version:"1.12.1.6",  name:"November Balance", date:"2023-11-13",
    buffs:["Chandelure","Clefable","Glaceon","Mimikyu","Talonflame"],
    nerfs:["Eldegoss","Mega Mewtwo X","Slowbro","Zacian"],
    tweaks:["Blastoise","Charizard","Venusaur"],
    notes:"Item Updates: Eject Button, Full Heal, Goal-Getter, Slow Smoke and more" },

  { version:"1.12.1.4",  name:"Halloween Balance", date:"2023-10-18",
    buffs:["Absol","Blaziken","Decidueye","Mew","Snorlax"],
    nerfs:["Blissey","Leafeon","Lapras","Mega Mewtwo Y","Urshifu"],
    tweaks:["Cramorant","Talonflame"], notes:"Halloween in Mer Stadium reruns" },

  { version:"1.12.1.2",  name:"Season 14 Start", date:"2023-09-07",
    buffs:["Aegislash","Gengar","Pikachu","Tsareena"],
    nerfs:["Alolan Ninetales","Mega Mewtwo X","Mega Mewtwo Y","Umbreon"],
    tweaks:[], notes:"Battle Pass Season 18, Ranked Season 14, New Items: Curse Incense, Curse Bangle" },

  { version:"1.11.1.8",  name:"August Balance", date:"2023-08-15",
    buffs:["Crustle","Garchomp","Talonflame","Tyranitar"],
    nerfs:[], tweaks:[], notes:"Shop update, Event update, Bug Fix, Text Fix" },

  { version:"1.11.1.7",  name:"Mewtwo Emergency", date:"2023-08-07",
    buffs:[], nerfs:["Mega Mewtwo X"], tweaks:["Decidueye"], notes:"Bug fixes, Text fixes" },

  { version:"1.11.1.4",  name:"Mewtwo Nerf", date:"2023-07-22",
    buffs:[], nerfs:["Mega Mewtwo X"], tweaks:[], notes:"" },
];

/* ── Pokémon roster ────────────────────────────────────────────────────────── */
const POKEMON = [
  { name:"Absol",             role:"Speedster",    type:"melee"  },
  { name:"Aegislash",         role:"All-Rounder",  type:"melee"  },
  { name:"Alcremie",          role:"Supporter",    type:"ranged" },
  { name:"Alolan Ninetales",  role:"Attacker",     type:"ranged" },
  { name:"Alolan Raichu",     role:"Speedster",    type:"ranged" },
  { name:"Armarouge",         role:"Attacker",     type:"ranged" },
  { name:"Azumarill",         role:"All-Rounder",  type:"melee"  },
  { name:"Blastoise",         role:"Defender",     type:"melee"  },
  { name:"Blaziken",          role:"All-Rounder",  type:"melee"  },
  { name:"Blissey",           role:"Supporter",    type:"melee"  },
  { name:"Buzzwole",          role:"All-Rounder",  type:"melee"  },
  { name:"Ceruledge",         role:"Speedster",    type:"melee"  },
  { name:"Chandelure",        role:"Attacker",     type:"ranged" },
  { name:"Charizard",         role:"All-Rounder",  type:"melee"  },
  { name:"Cinderace",         role:"Attacker",     type:"ranged" },
  { name:"Clefable",          role:"Supporter",    type:"ranged" },
  { name:"Comfey",            role:"Supporter",    type:"ranged" },
  { name:"Cramorant",         role:"Attacker",     type:"ranged" },
  { name:"Crustle",           role:"Defender",     type:"melee"  },
  { name:"Darkrai",           role:"Attacker",     type:"ranged" },
  { name:"Decidueye",         role:"Attacker",     type:"ranged" },
  { name:"Delphox",           role:"Attacker",     type:"ranged" },
  { name:"Dhelmise",          role:"Attacker",     type:"ranged" },
  { name:"Dodrio",            role:"Speedster",    type:"melee"  },
  { name:"Dragapult",         role:"Attacker",     type:"ranged" },
  { name:"Dragonite",         role:"All-Rounder",  type:"melee"  },
  { name:"Duraludon",         role:"Attacker",     type:"ranged" },
  { name:"Eldegoss",          role:"Supporter",    type:"ranged" },
  { name:"Empoleon",          role:"Defender",     type:"melee"  },
  { name:"Espeon",            role:"Attacker",     type:"ranged" },
  { name:"Falinks",           role:"All-Rounder",  type:"melee"  },
  { name:"Galarian Rapidash", role:"Speedster",    type:"melee"  },
  { name:"Garchomp",          role:"All-Rounder",  type:"melee"  },
  { name:"Gardevoir",         role:"Attacker",     type:"ranged" },
  { name:"Gengar",            role:"Speedster",    type:"melee"  },
  { name:"Glaceon",           role:"Attacker",     type:"ranged" },
  { name:"Goodra",            role:"Defender",     type:"ranged" },
  { name:"Greedent",          role:"Defender",     type:"melee"  },
  { name:"Greninja",          role:"Attacker",     type:"ranged" },
  { name:"Gyarados",          role:"All-Rounder",  type:"melee"  },
  { name:"Ho-Oh",             role:"Supporter",    type:"ranged" },
  { name:"Hoopa",             role:"Supporter",    type:"ranged" },
  { name:"Inteleon",          role:"Attacker",     type:"ranged" },
  { name:"Lapras",            role:"Defender",     type:"ranged" },
  { name:"Latias",            role:"Supporter",    type:"ranged" },
  { name:"Latios",            role:"Attacker",     type:"ranged" },
  { name:"Leafeon",           role:"Speedster",    type:"melee"  },
  { name:"Lucario",           role:"All-Rounder",  type:"melee"  },
  { name:"Machamp",           role:"All-Rounder",  type:"melee"  },
  { name:"Mamoswine",         role:"Defender",     type:"melee"  },
  { name:"Mega Charizard X",  role:"All-Rounder",  type:"melee"  },
  { name:"Mega Charizard Y",  role:"Attacker",     type:"ranged" },
  { name:"Mega Gyarados",     role:"All-Rounder",  type:"melee"  },
  { name:"Mega Lucario",      role:"All-Rounder",  type:"melee"  },
  { name:"Mega Mewtwo X",     role:"All-Rounder",  type:"melee"  },
  { name:"Mega Mewtwo Y",     role:"Attacker",     type:"ranged" },
  { name:"Meowscarada",       role:"Speedster",    type:"melee"  },
  { name:"Meowth",            role:"Speedster",    type:"melee"  },
  { name:"Metagross",         role:"All-Rounder",  type:"melee"  },
  { name:"Mew",               role:"Attacker",     type:"ranged" },
  { name:"Mimikyu",           role:"All-Rounder",  type:"melee"  },
  { name:"Miraidon",          role:"Attacker",     type:"ranged" },
  { name:"Moltres",           role:"Attacker",     type:"ranged" },
  { name:"Mr. Mime",          role:"Supporter",    type:"ranged" },
  { name:"Pawmot",            role:"All-Rounder",  type:"melee"  },
  { name:"Pikachu",           role:"Attacker",     type:"ranged" },
  { name:"Psyduck",           role:"Supporter",    type:"ranged" },
  { name:"Sableye",           role:"Supporter",    type:"melee"  },
  { name:"Scizor",            role:"All-Rounder",  type:"melee"  },
  { name:"Sirfetch'd",        role:"All-Rounder",  type:"melee"  },
  { name:"Slowbro",           role:"Defender",     type:"ranged" },
  { name:"Snorlax",           role:"Defender",     type:"melee"  },
  { name:"Suicune",           role:"Attacker",     type:"ranged" },
  { name:"Sylveon",           role:"Attacker",     type:"ranged" },
  { name:"Talonflame",        role:"Speedster",    type:"melee"  },
  { name:"Tinkaton",          role:"Defender",     type:"melee"  },
  { name:"Trevenant",         role:"Defender",     type:"melee"  },
  { name:"Tsareena",          role:"All-Rounder",  type:"melee"  },
  { name:"Tyranitar",         role:"All-Rounder",  type:"melee"  },
  { name:"Umbreon",           role:"Defender",     type:"melee"  },
  { name:"Urshifu",           role:"All-Rounder",  type:"melee"  },
  { name:"Vaporeon",          role:"Attacker",     type:"ranged" },
  { name:"Venusaur",          role:"Attacker",     type:"ranged" },
  { name:"Wigglytuff",        role:"Supporter",    type:"ranged" },
  { name:"Zacian",            role:"All-Rounder",  type:"melee"  },
  { name:"Zapdos",            role:"Attacker",     type:"ranged" },
  { name:"Zeraora",           role:"Speedster",    type:"melee"  },
  { name:"Zoroark",           role:"Speedster",    type:"melee"  },
];